# Generated by Django 3.1.2 on 2020-10-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201003_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='emailid',
            field=models.CharField(default='a@gmail.com', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Course1',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='Course2',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='Course3',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=150),
        ),
    ]
